# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f6571f3312567919e4052392a41335662cf34d95bb107608f05b35fcdef23fddfce6a2adf9a356c51b6d5e94364d27526439202cb853d9ab33415ed517f03b4

test:
  secret_key_base: 59908a21a12cf5bff20edf876fd7aed6e72a3c1e96d81c04db6f622f56bcbf7d9086f89bcf6ec08f8426dcfb0e89305b7e08dbf02c25d3d817db0d4c8edde870

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
